import { z } from 'zod';
export const uuid = z.string().uuid();
export const source = z.enum(['manual','ai_text','image','integration','seed']).default('manual');
export const foodItem = z.object({ foodName:z.string().min(1), quantity:z.number().nonnegative().optional(), unit:z.string().optional(), calories:z.number().nonnegative().optional(), protein:z.number().nonnegative().optional(), carbs:z.number().nonnegative().optional(), fat:z.number().nonnegative().optional(), fiber:z.number().nonnegative().optional() });
export const logFood = z.object({ userId:uuid, mealType:z.string().optional(), notes:z.string().optional(), source, items:z.array(foodItem).min(1) });
const baseWorkout = z.object({ userId:uuid, workoutType:z.enum(['gym','walk','swim','run','cycle','yoga','sports','other']), startTime:z.string().datetime().optional(), endTime:z.string().datetime().optional(), durationMinutes:z.number().int().positive().optional(), caloriesBurned:z.number().int().nonnegative().optional(), source, notes:z.string().optional() });
export const strengthSet = z.object({ setNumber:z.number().int().positive(), reps:z.number().int().nonnegative().optional(), weight:z.number().nonnegative().optional(), rir:z.number().int().min(0).max(10).optional(), rpe:z.number().min(0).max(10).optional(), completed:z.boolean().default(true) });
export const strengthExercise = z.object({ exerciseName:z.string().min(1), muscleGroup:z.string().optional(), equipment:z.string().optional(), orderIndex:z.number().int().nonnegative(), sets:z.array(strengthSet).min(1) });
export const logStrengthWorkout = baseWorkout.extend({ workoutType:z.literal('gym').default('gym'), exercises:z.array(strengthExercise).min(1) });
export const logCardio = baseWorkout.extend({ workoutType:z.enum(['walk','swim','run','cycle','sports','other']), activity:z.string().min(1), distance:z.number().nonnegative().optional(), steps:z.number().int().nonnegative().optional(), pace:z.string().optional(), averageHr:z.number().int().positive().optional(), maxHr:z.number().int().positive().optional(), elevation:z.number().optional(), laps:z.number().int().nonnegative().optional(), poolLength:z.number().positive().optional() });
export const logSleep = z.object({ userId:uuid, bedtime:z.string().datetime(), wakeTime:z.string().datetime(), duration:z.number().int().positive().optional(), quality:z.number().int().min(1).max(5).optional(), source });
export const logWeight = z.object({ userId:uuid, weight:z.number().positive(), bodyFat:z.number().nonnegative().optional(), muscleMass:z.number().nonnegative().optional(), visceralFat:z.number().nonnegative().optional(), source });
export const uploadAttachment = z.object({ userId:uuid, attachmentType:z.enum(['meal_photo','zepp_screenshot','progress_photo','other']), fileName:z.string().min(1), contentType:z.string().min(1), base64:z.string().min(1) });
export const attachImage = z.object({ attachmentId:uuid, linkedTable:z.enum(['food_logs','workout_sessions','cardio_sessions','sleep_logs','weight_logs']), linkedRecordId:uuid });
export const recentLogs = z.object({ userId:uuid, type:z.enum(['food','strength','cardio','sleep','weight']), limit:z.number().int().min(1).max(100).default(10) });
export const todaySummary = z.object({ userId:uuid, timezone:z.string().default('UTC') });
export const updateLog = z.object({ table:z.enum(['food_logs','food_items','workout_sessions','strength_exercises','strength_sets','cardio_sessions','sleep_logs','weight_logs']), id:uuid, patch:z.record(z.unknown()).refine(v=>Object.keys(v).length>0,'patch must not be empty') });
export const deleteLog = z.object({ table:updateLog.shape.table, id:uuid });
export type LogFoodInput = z.infer<typeof logFood>;
