import { boolean, index, integer, numeric, pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const sourceEnum = pgEnum('source', ['manual', 'ai_text', 'image', 'integration', 'seed']);
export const workoutTypeEnum = pgEnum('workout_type', ['gym', 'walk', 'swim', 'run', 'cycle', 'yoga', 'sports', 'other']);
export const attachmentTypeEnum = pgEnum('attachment_type', ['meal_photo', 'zepp_screenshot', 'progress_photo', 'other']);

const audit = { createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(), deletedAt: timestamp('deleted_at', { withTimezone: true }) };
export const foodLogs = pgTable('food_logs', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull(), mealType: text('meal_type'), totalCalories: numeric('total_calories'), totalProtein: numeric('total_protein'), totalCarbs: numeric('total_carbs'), totalFat: numeric('total_fat'), totalFiber: numeric('total_fiber'), notes: text('notes'), source: sourceEnum('source').default('manual').notNull(), ...audit }, t => ({ userIdx: index('food_logs_user_idx').on(t.userId) }));
export const foodItems = pgTable('food_items', { id: uuid('id').defaultRandom().primaryKey(), foodLogId: uuid('food_log_id').references(() => foodLogs.id).notNull(), foodName: text('food_name').notNull(), quantity: numeric('quantity'), unit: text('unit'), calories: numeric('calories'), protein: numeric('protein'), carbs: numeric('carbs'), fat: numeric('fat'), fiber: numeric('fiber'), ...audit });
export const workoutSessions = pgTable('workout_sessions', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull(), workoutType: workoutTypeEnum('workout_type').notNull(), startTime: timestamp('start_time', { withTimezone: true }), endTime: timestamp('end_time', { withTimezone: true }), durationMinutes: integer('duration_minutes'), caloriesBurned: integer('calories_burned'), source: sourceEnum('source').default('manual').notNull(), notes: text('notes'), ...audit });
export const strengthExercises = pgTable('strength_exercises', { id: uuid('id').defaultRandom().primaryKey(), workoutSessionId: uuid('workout_session_id').references(() => workoutSessions.id).notNull(), exerciseName: text('exercise_name').notNull(), muscleGroup: text('muscle_group'), equipment: text('equipment'), orderIndex: integer('order_index').notNull(), ...audit });
export const strengthSets = pgTable('strength_sets', { id: uuid('id').defaultRandom().primaryKey(), strengthExerciseId: uuid('strength_exercise_id').references(() => strengthExercises.id).notNull(), setNumber: integer('set_number').notNull(), reps: integer('reps'), weight: numeric('weight'), rir: integer('rir'), rpe: numeric('rpe'), completed: boolean('completed').default(true).notNull(), ...audit });
export const cardioSessions = pgTable('cardio_sessions', { id: uuid('id').defaultRandom().primaryKey(), workoutSessionId: uuid('workout_session_id').references(() => workoutSessions.id).notNull(), activity: text('activity').notNull(), distance: numeric('distance'), steps: integer('steps'), pace: text('pace'), averageHr: integer('average_hr'), maxHr: integer('max_hr'), elevation: numeric('elevation'), laps: integer('laps'), poolLength: numeric('pool_length'), ...audit });
export const sleepLogs = pgTable('sleep_logs', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull(), bedtime: timestamp('bedtime', { withTimezone: true }).notNull(), wakeTime: timestamp('wake_time', { withTimezone: true }).notNull(), duration: integer('duration').notNull(), quality: integer('quality'), source: sourceEnum('source').default('manual').notNull(), ...audit });
export const weightLogs = pgTable('weight_logs', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull(), weight: numeric('weight').notNull(), bodyFat: numeric('body_fat'), muscleMass: numeric('muscle_mass'), visceralFat: numeric('visceral_fat'), source: sourceEnum('source').default('manual').notNull(), ...audit });
export const attachments = pgTable('attachments', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull(), attachmentType: attachmentTypeEnum('attachment_type').notNull(), storagePath: text('storage_path').notNull(), linkedTable: text('linked_table'), linkedRecordId: uuid('linked_record_id'), uploadedAt: timestamp('uploaded_at', { withTimezone: true }).defaultNow().notNull(), ...audit });
